name: Build and Release Extension

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  build:
    name: Build Chrome and Firefox Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Prepare Chrome Extension
        run: |
          cp manifest/manifest-chrome.json src/manifest.json
          mkdir -p dist/chrome
          cd src
          zip -r ../dist/chrome/extension.zip *
          cd ..

      - name: Install Chrome for extension signing
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Sign Chrome Extension
        env:
          PEM: ${{ secrets.PEM }}
        run: |
          echo "$PEM" > private-key.pem
          mkdir -p dist/chrome/signed
          # Use Chrome's pack extension tool to sign the extension
          google-chrome --pack-extension=src --pack-extension-key=private-key.pem
          if [ -f "src.crx" ]; then
            mv src.crx dist/chrome/signed/extension.crx
          else
            echo "Chrome signing failed, using unsigned zip instead"
            cp dist/chrome/extension.zip dist/chrome/signed/extension.zip
          fi
          # Clean up private key
          rm private-key.pem

      - name: Prepare Firefox Extension
        run: |
          cp manifest/manifest-firefox.json src/manifest.json
          mkdir -p dist/firefox
          cd src
          zip -r ../dist/firefox/extension.xpi *
          cd ..

      - name: Upload Chrome and Firefox artifacts
        uses: actions/upload-artifact@v3
        with:
          name: browser-extensions
          path: |
            dist/chrome/signed/
            dist/firefox/

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Download extension artifacts
        uses: actions/download-artifact@v3
        with:
          name: browser-extensions
          path: dist

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release --debug