name: Build and Release

# This workflow is manually triggered via the GitHub Actions UI
# It builds the extension for Chrome and Firefox and creates a new release
# The release type (patch, minor, major) is determined automatically based on commit messages
# Optional custom release notes can be provided

on:
  workflow_dispatch:
    description: 'Manually trigger a new release build and deployment'
    inputs:
      release_notes:
        description: 'Custom release notes (optional)'
        required: false
        type: 'string'

jobs:
  build:
    name: Build Chrome and Firefox Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Prepare Chrome Extension
        run: |
          cp manifest/manifest-chrome.json src/manifest.json
          mkdir -p dist/chrome
          cd src
          zip -r ../dist/chrome/extension.zip *
          cd ..

      - name: Install Chrome for extension signing
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor | sudo tee /usr/share/keyrings/google-chrome.gpg > /dev/null
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Sign Chrome Extension
        env:
          PEM: ${{ secrets.PEM }}
        run: |
          echo "$PEM" > private-key.pem
          mkdir -p dist/chrome/signed
          # Use Chrome's pack extension tool to sign the extension
          google-chrome --pack-extension=src --pack-extension-key=private-key.pem
          if [ -f "src.crx" ]; then
            mv src.crx dist/chrome/signed/extension.crx
          else
            echo "Chrome signing failed, using unsigned zip instead"
            cp dist/chrome/extension.zip dist/chrome/signed/extension.zip
          fi
          # Clean up private key
          rm private-key.pem

      - name: Prepare Firefox Extension
        run: |
          cp manifest/manifest-firefox.json src/manifest.json
          mkdir -p dist/firefox
          cd src
          zip -r ../dist/firefox/extension.xpi *
          cd ..

      - name: Upload Chrome and Firefox artifacts
        uses: actions/upload-artifact@v4
        with:
          name: browser-extensions
          path: |
            dist/chrome/signed/
            dist/firefox/

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Download extension artifacts
        uses: actions/download-artifact@v4
        with:
          name: browser-extensions
          path: dist

      - name: Prepare Custom Release Notes
        if: ${{ github.event.inputs.release_notes != '' }}
        run: |
          # Create a temporary release notes file if custom notes are provided
          echo '${{ github.event.inputs.release_notes }}' > RELEASE_NOTES.md
          # Create a commit with the custom release notes
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add RELEASE_NOTES.md
          git commit -m "docs: add custom release notes [skip ci]"

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Run semantic-release to automatically determine the release type based on commit messages
          npx semantic-release --debug
